-- =====================================================================
--  OBD Lighting — seed data
--
--  10 categories (exactly the client's two handwritten lists),
--  36 main products with spec sheets, site settings.
--  8 real photographs live in server/uploads/products/.
--
--  Prices are Bangladesh market ESTIMATES — correct them in the admin panel.
--
--  mysql -u root -p obd_lighting < database/seed.sql
-- =====================================================================

USE obd_lighting;
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE product_specs; TRUNCATE TABLE product_images; TRUNCATE TABLE products;
TRUNCATE TABLE subcategories; TRUNCATE TABLE categories; TRUNCATE TABLE settings;
SET FOREIGN_KEY_CHECKS = 1;

-- ---------- categories ----------
INSERT INTO categories (id, name, name_bn, blurb, blurb_bn, icon, sort_order) VALUES
  ('street', 'LED Street Light', 'LED স্ট্রিট লাইট', 'Road, campus & solar', 'রাস্তা, ক্যাম্পাস ও সোলার', 'street', 0),
  ('industrial', 'LED Industrial Light', 'LED ইন্ডাস্ট্রিয়াল লাইট', 'Weatherproof & heavy duty', 'ওয়েদারপ্রুফ ও হেভি ডিউটি', 'flood', 10),
  ('tubeshade', 'LED Industrial Tube Light & Shade', 'LED ইন্ডাস্ট্রিয়াল টিউব লাইট ও শেড', 'Single & double shade', 'সিঙ্গেল ও ডাবল শেড', 'shadeDouble', 20),
  ('panel', 'LED Panel Light', 'LED প্যানেল লাইট', 'Louver, conceal & surface', 'লুভার, কনসিল ও সারফেস', 'panelLouver', 30),
  ('bulb', 'LED AC / DC Bulb', 'LED AC / DC বাল্ব', '220 V AC & 12 V DC', '২২০ ভোল্ট AC ও ১২ ভোল্ট DC', 'bulbA', 40),
  ('highbay', 'LED High Bay Light', 'LED হাই বে লাইট', 'UFO, 100–240 W', 'UFO, ১০০–২৪০ ওয়াট', 'highbay', 50),
  ('downtrack', 'LED Down & Track Light', 'LED ডাউন ও ট্র্যাক লাইট', 'COB downlight & track', 'COB ডাউনলাইট ও ট্র্যাক', 'track', 60),
  ('flood', 'LED Flood Light', 'LED ফ্লাড লাইট', 'IP66 outdoor', 'IP66 আউটডোর', 'flood', 70),
  ('wiring', 'Switches & Sockets', 'সুইচ ও সকেট', 'Modern plate range', 'মডার্ন প্লেট রেঞ্জ', 'switchPlate', 80),
  ('protection', 'Breakers & DB Boxes', 'ব্রেকার ও DB বক্স', 'MCB, RCCB, SPN & TPN', 'MCB, RCCB, SPN ও TPN', 'ballast', 90);

-- ---------- sub-categories ----------
INSERT INTO subcategories (category_id, name, name_bn, sort_order) VALUES
  ('street', '30–60 W street light', '৩০–৬০ ওয়াট স্ট্রিট লাইট', 0),
  ('street', '80–150 W street light', '৮০–১৫০ ওয়াট স্ট্রিট লাইট', 10),
  ('street', '200 W and above', '২০০ ওয়াট ও তার বেশি', 20),
  ('street', 'Solar street light', 'সোলার স্ট্রিট লাইট', 30),
  ('street', 'Pole, arm & bracket', 'পোল, আর্ম ও ব্র্যাকেট', 40),
  ('industrial', 'Weatherproof fitting', 'ওয়েদারপ্রুফ ফিটিং', 0),
  ('industrial', 'Bulkhead light', 'বাল্কহেড লাইট', 10),
  ('industrial', 'Well glass light', 'ওয়েল গ্লাস লাইট', 20),
  ('industrial', 'Explosion proof', 'এক্সপ্লোশন প্রুফ', 30),
  ('tubeshade', 'T8 LED tube', 'T8 LED টিউব', 0),
  ('tubeshade', 'T5 batten', 'T5 ব্যাটেন', 10),
  ('tubeshade', 'Single shade', 'সিঙ্গেল শেড', 20),
  ('tubeshade', 'Double shade', 'ডাবল শেড', 30),
  ('tubeshade', 'Cover / SS double shade', 'কভার / SS ডাবল শেড', 40),
  ('panel', 'Conceal type (round)', 'কনসিল টাইপ (গোল)', 0),
  ('panel', 'Conceal type (square)', 'কনসিল টাইপ (চারকোনা)', 10),
  ('panel', 'Surface type', 'সারফেস টাইপ', 20),
  ('panel', 'Louver type 2×2', 'লুভার টাইপ ২×২', 30),
  ('bulb', 'AC bulb E27 / B22', 'AC বাল্ব E27 / B22', 0),
  ('bulb', 'T-bulb (high watt)', 'T-বাল্ব (হাই ওয়াট)', 10),
  ('bulb', 'DC bulb 12 V (IPS / solar)', 'DC বাল্ব ১২ ভোল্ট (IPS / সোলার)', 20),
  ('highbay', 'UFO high bay 100 W', 'UFO হাই বে ১০০ ওয়াট', 0),
  ('highbay', 'UFO high bay 150 W', 'UFO হাই বে ১৫০ ওয়াট', 10),
  ('highbay', 'UFO high bay 200 W+', 'UFO হাই বে ২০০ ওয়াট+', 20),
  ('highbay', 'Hook & hanging kit', 'হুক ও ঝোলানোর কিট', 30),
  ('downtrack', 'COB recessed downlight', 'COB রিসেসড ডাউনলাইট', 0),
  ('downtrack', 'Surface downlight', 'সারফেস ডাউনলাইট', 10),
  ('downtrack', 'Track light head', 'ট্র্যাক লাইট হেড', 20),
  ('downtrack', 'Track rail & connector', 'ট্র্যাক রেল ও কানেক্টর', 30),
  ('flood', '20–50 W flood', '২০–৫০ ওয়াট ফ্লাড', 0),
  ('flood', '100–200 W flood', '১০০–২০০ ওয়াট ফ্লাড', 10),
  ('flood', '300 W and above', '৩০০ ওয়াট ও তার বেশি', 20),
  ('wiring', '1 & 2 gang switch', '১ ও ২ গ্যাং সুইচ', 0),
  ('wiring', '3 & 4 gang switch', '৩ ও ৪ গ্যাং সুইচ', 10),
  ('wiring', '13A socket & switch', '১৩A সকেট ও সুইচ', 20),
  ('wiring', 'Holder & accessories', 'হোল্ডার ও অ্যাকসেসরিজ', 30),
  ('protection', 'MCB single & triple pole', 'MCB সিঙ্গেল ও ট্রিপল পোল', 0),
  ('protection', 'RCCB / RCBO', 'RCCB / RCBO', 10),
  ('protection', 'Changeover switch', 'চেঞ্জওভার সুইচ', 20),
  ('protection', 'DB box SPN / TPN', 'DB বক্স SPN / TPN', 30);

-- ---------- products ----------
INSERT INTO products (slug, category_id, name, name_bn, sku, price, old_price,
                      wattage, cct, art, stock, is_featured, is_new, sort_order) VALUES
  ('street-30', 'street', 'Street Light 30W IP66', 'স্ট্রিট লাইট ৩০ ওয়াট IP66', 'OBD-SL-030', 2400, 2750, 30, 6500, 'street', 60, 0, 0, 0),
  ('street-60', 'street', 'Street Light 60W IP66', 'স্ট্রিট লাইট ৬০ ওয়াট IP66', 'OBD-SL-060', 3900, NULL, 60, 6500, 'street', 42, 1, 0, 10),
  ('street-100', 'street', 'Street Light 100W IP66', 'স্ট্রিট লাইট ১০০ ওয়াট IP66', 'OBD-SL-100', 6200, NULL, 100, 6500, 'street', 24, 0, 0, 20),
  ('ind-wp-40', 'industrial', 'Weatherproof Fitting 2×20W IP65', 'ওয়েদারপ্রুফ ফিটিং ২×২০ ওয়াট IP65', 'OBD-IW-240', 2600, 2950, 40, 6500, 'shadeCover', 48, 1, 0, 30),
  ('ind-bulk-15', 'industrial', 'Bulkhead Light 15W IP65', 'বাল্কহেড লাইট ১৫ ওয়াট IP65', 'OBD-IB-015', 850, NULL, 15, 6500, 'panelRound', 96, 0, 0, 40),
  ('ind-well-50', 'industrial', 'Well Glass Light 50W IP65', 'ওয়েল গ্লাস লাইট ৫০ ওয়াট IP65', 'OBD-IG-050', 3200, NULL, 50, 5700, 'highbay', 22, 0, 1, 50),
  ('tube-18', 'tubeshade', 'T8 LED Tube 18W 4ft', 'T8 LED টিউব ১৮ ওয়াট ৪ ফুট', 'OBD-T8-18', 350, 420, 18, 6500, 'tube', 420, 1, 0, 60),
  ('shade-single-20', 'tubeshade', 'Industrial Single Shade 20W 4ft', 'ইন্ডাস্ট্রিয়াল সিঙ্গেল শেড ২০ ওয়াট ৪ ফুট', 'OBD-IS-120', 1350, NULL, 20, 6500, 'shadeSingle', 88, 0, 0, 70),
  ('shade-double-40', 'tubeshade', 'Industrial Double Shade 2×20W 4ft', 'ইন্ডাস্ট্রিয়াল ডাবল শেড ২×২০ ওয়াট ৪ ফুট', 'OBD-ID-240', 2400, 2750, 40, 6500, 'shadeDouble', 64, 1, 0, 80),
  ('panel-r-18', 'panel', 'Conceal Panel Round 18W', 'কনসিল প্যানেল গোল ১৮ ওয়াট', 'OBD-PR-018', 550, 640, 18, 6500, 'panelRound', 260, 1, 0, 90),
  ('panel-s-24', 'panel', 'Conceal Panel Square 24W', 'কনসিল প্যানেল চারকোনা ২৪ ওয়াট', 'OBD-PS-024', 750, NULL, 24, 6500, 'panelSquare', 180, 0, 0, 100),
  ('panel-l-40', 'panel', 'Louver Panel 40W 2×2', 'লুভার প্যানেল ৪০ ওয়াট ২×২', 'OBD-PL-040', 2200, NULL, 40, 4000, 'panelLouver', 54, 0, 1, 110),
  ('bulb-ac-9', 'bulb', 'AC Bulb 9W E27', 'AC বাল্ব ৯ ওয়াট E27', 'OBD-AB-009', 190, 240, 9, 6500, 'bulbA', 640, 1, 0, 120),
  ('bulb-ac-12', 'bulb', 'AC Bulb 12W B22', 'AC বাল্ব ১২ ওয়াট B22', 'OBD-AB-012', 240, NULL, 12, 3000, 'bulbA', 480, 0, 0, 130),
  ('bulb-t-36', 'bulb', 'T-Bulb 36W E27 High Watt', 'T-বাল্ব ৩৬ ওয়াট E27', 'OBD-AT-036', 780, NULL, 36, 6500, 'bulbT', 126, 0, 0, 140),
  ('bulb-dc-9', 'bulb', 'DC Bulb 9W 12V — IPS / Solar', 'DC বাল্ব ৯ ওয়াট ১২ ভোল্ট', 'OBD-DB-009', 300, NULL, 9, 6500, 'bulbA', 310, 1, 1, 150),
  ('hb-100', 'highbay', 'UFO High Bay 100W', 'UFO হাই বে ১০০ ওয়াট', 'OBD-HB-100', 4800, NULL, 100, 5700, 'highbay', 34, 0, 0, 160),
  ('hb-150', 'highbay', 'UFO High Bay 150W', 'UFO হাই বে ১৫০ ওয়াট', 'OBD-HB-150', 6800, 7500, 150, 5700, 'highbay', 28, 1, 0, 170),
  ('hb-200', 'highbay', 'UFO High Bay 200W', 'UFO হাই বে ২০০ ওয়াট', 'OBD-HB-200', 8900, NULL, 200, 5700, 'highbay', 16, 0, 0, 180),
  ('dl-7', 'downtrack', 'COB Downlight 7W', 'COB ডাউনলাইট ৭ ওয়াট', 'OBD-DL-007', 320, NULL, 7, 3000, 'downlight', 380, 0, 0, 190),
  ('dl-12', 'downtrack', 'COB Downlight 12W', 'COB ডাউনলাইট ১২ ওয়াট', 'OBD-DL-012', 480, 550, 12, 3000, 'downlight', 290, 1, 0, 200),
  ('tl-20', 'downtrack', 'Track Light Head 20W', 'ট্র্যাক লাইট হেড ২০ ওয়াট', 'OBD-TL-020', 1250, NULL, 20, 3000, 'track', 72, 0, 1, 210),
  ('fl-20', 'flood', 'Flood Light 20W IP66', 'ফ্লাড লাইট ২০ ওয়াট IP66', 'OBD-FL-020', 550, 650, 20, 6500, 'flood', 240, 0, 0, 220),
  ('fl-50', 'flood', 'Flood Light 50W IP66', 'ফ্লাড লাইট ৫০ ওয়াট IP66', 'OBD-FL-050', 1100, 1300, 50, 6500, 'flood', 150, 1, 0, 230),
  ('fl-100', 'flood', 'Flood Light 100W IP66', 'ফ্লাড লাইট ১০০ ওয়াট IP66', 'OBD-FL-100', 2150, NULL, 100, 6500, 'flood', 86, 0, 0, 240),
  ('fl-200', 'flood', 'Flood Light 200W IP66', 'ফ্লাড লাইট ২০০ ওয়াট IP66', 'OBD-FL-200', 3600, NULL, 200, 6500, 'flood', 38, 0, 0, 250),
  ('sw-1g', 'wiring', '1-Gang Switch — Modern White', '১-গ্যাং সুইচ — মডার্ন হোয়াইট', 'OBD-SW-1G', 150, NULL, NULL, NULL, 'switchPlate', 820, 0, 0, 260),
  ('sw-2g', 'wiring', '2-Gang Switch — Modern White', '২-গ্যাং সুইচ — মডার্ন হোয়াইট', 'OBD-SW-2G', 220, NULL, NULL, NULL, 'switchPlate', 640, 1, 0, 270),
  ('so-13a', 'wiring', '13A Socket + Switch — White', '১৩A সকেট + সুইচ — হোয়াইট', 'OBD-SO-13A', 290, 340, NULL, NULL, 'socket', 520, 1, 0, 280),
  ('mcb-32', 'protection', 'MCB 32A Single Pole 6kA', 'MCB ৩২A সিঙ্গেল পোল ৬kA', 'OBD-MCB-32', 380, NULL, NULL, NULL, 'ballast', 360, 0, 0, 290),
  ('rccb-63', 'protection', 'RCCB 63A 2P 30mA', 'RCCB ৬৩A ২P ৩০mA', 'OBD-RCB-63', 1800, 2100, NULL, NULL, 'ballast', 74, 1, 0, 300),
  ('db-8', 'protection', '8-Way SPN Distribution Box', '৮-ওয়ে SPN ডিস্ট্রিবিউশন বক্স', 'OBD-DB-08S', 1700, 1950, NULL, NULL, 'ballast', 52, 0, 1, 310);

-- ---------- products added from the shop's own photographs ----------
INSERT INTO products (slug, category_id, name, name_bn, sku, price, old_price,
                      wattage, cct, art, stock, is_featured, is_new, sort_order) VALUES
  ('batten-36', 'tubeshade', 'Slim Batten Light 36W 4ft', 'স্লিম ব্যাটেন লাইট ৩৬ ওয়াট ৪ ফুট', 'OBD-SB-036', 750, 890, 36, 6500, 'tube', 180, 1, 1, 75),
  ('sdl-12-white', 'downtrack', 'Surface Downlight 12W Round — White', 'সারফেস ডাউনলাইট ১২ ওয়াট গোল — সাদা', 'OBD-SD-12W', 620, 720, 12, 3000, 'downlight', 240, 1, 1, 205),
  ('sdl-12-black', 'downtrack', 'Surface Downlight 12W Round — Black & Gold', 'সারফেস ডাউনলাইট ১২ ওয়াট গোল — কালো ও গোল্ড', 'OBD-SD-12B', 780, NULL, 12, 3000, 'downlight', 160, 0, 1, 206),
  ('cfl-25', 'bulb', 'Spiral Energy Saving Bulb 25W E27 (CFL)', 'স্পাইরাল এনার্জি সেভিং বাল্ব ২৫ ওয়াট E27 (CFL)', 'OBD-CF-025', 320, 380, 25, 6500, 'bulbA', 210, 0, 0, 155);

-- ---------- photographs supplied by the shop ----------
UPDATE products SET image = 'bulb-led-single.jpg'         WHERE slug = 'bulb-ac-9';
UPDATE products SET image = 'cfl-spiral.jpg'              WHERE slug = 'cfl-25';
UPDATE products SET image = 'downlight-surface-white.jpg' WHERE slug = 'sdl-12-white';
UPDATE products SET image = 'downlight-surface-black.jpg' WHERE slug = 'sdl-12-black';
UPDATE products SET image = 'flood-ip66.jpg'              WHERE slug IN ('fl-20', 'fl-50', 'fl-100', 'fl-200');
UPDATE products SET image = 'batten-slim.jpg'             WHERE slug = 'batten-36';
UPDATE products SET image = 'shade-double.jpg'            WHERE slug IN ('shade-double-40', 'shade-single-20');

-- ---------- specification sheets ----------
INSERT INTO product_specs (product_id, spec_key, spec_value, sort_order) VALUES
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Wattage', '30 W', 0),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Luminous flux', '3,300 lm', 10),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Type', 'Die-cast housing, Type II optic', 30),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Pole fit', 'Ø 48–60 mm', 40),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'street-30'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Wattage', '60 W', 0),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Luminous flux', '6,600 lm', 10),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Type', 'Die-cast housing, Type II optic', 30),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Pole fit', 'Ø 48–60 mm', 40),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'street-60'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Wattage', '100 W', 0),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Luminous flux', '11,000 lm', 10),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Type', 'Die-cast housing, Type II optic', 30),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Pole fit', 'Ø 60–76 mm', 40),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'street-100'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Wattage', '40 W', 0),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Luminous flux', '4,400 lm', 10),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Type', 'Sealed PC diffuser, twin tube', 30),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Length', '1,260 mm', 40),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'IP', 'IP65', 50),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'ind-wp-40'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Wattage', '15 W', 0),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Luminous flux', '1,650 lm', 10),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Type', 'Round bulkhead, PC body', 30),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Size', 'Ø 250 mm', 40),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'IP', 'IP65', 50),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'ind-bulk-15'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Wattage', '50 W', 0),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Luminous flux', '5,500 lm', 10),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'CCT', '5700 K', 20),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Type', 'Die-cast well glass, toughened cover', 30),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'IP', 'IP65', 40),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Input voltage', 'AC 85–265 V', 50),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Frequency', '50–60 Hz', 60),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Output voltage', 'DC 36–42 V', 70),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Power factor', 'PF > 0.96', 80),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'THD', '< 8%', 90),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Driver', 'Isolated', 100),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'CRI', 'Ra > 80–90', 110),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Efficacy', '110 lm/W', 120),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Lumen maintenance', '97% up to 10,000 h', 130),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Service life', '50,000 hours', 140),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Material', 'Aluminium + PC diffuser', 150),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Operating temp', '−20 °C to 45 °C', 160),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Certification', 'CE · UL · LM-80 · RoHS', 170),
  ((SELECT id FROM products WHERE slug = 'ind-well-50'), 'Warranty', '3 years (replacement)', 180),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Wattage', '18 W', 0),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Luminous flux', '1,980 lm', 10),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Type', 'T8 integrated tube', 30),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Cap', 'G13', 40),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Length', '1,200 mm', 50),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'IP', 'IP20', 60),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Input voltage', 'AC 85–265 V', 70),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Frequency', '50–60 Hz', 80),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Output voltage', 'DC 36–42 V', 90),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Power factor', 'PF > 0.96', 100),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'THD', '< 8%', 110),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Driver', 'Isolated', 120),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'CRI', 'Ra > 80–90', 130),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Efficacy', '110 lm/W', 140),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Lumen maintenance', '97% up to 10,000 h', 150),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Service life', '50,000 hours', 160),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Material', 'Aluminium + PC diffuser', 170),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Operating temp', '−20 °C to 45 °C', 180),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Certification', 'CE · UL · LM-80 · RoHS', 190),
  ((SELECT id FROM products WHERE slug = 'tube-18'), 'Warranty', '3 years (replacement)', 200),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Wattage', '20 W', 0),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Luminous flux', '2,200 lm', 10),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Type', 'Single shade, powder-coated MS', 30),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Length', '1,260 mm', 40),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'IP', 'IP54', 50),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'shade-single-20'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Wattage', '40 W', 0),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Luminous flux', '4,400 lm', 10),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Type', 'Double shade, deep reflector', 30),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Length', '1,260 mm', 40),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Watt options', '36 / 40 / 44 / 48 / 52 / 56 / 60 W', 50),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'IP', 'IP54', 60),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Input voltage', 'AC 85–265 V', 70),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Frequency', '50–60 Hz', 80),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Output voltage', 'DC 36–42 V', 90),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Power factor', 'PF > 0.96', 100),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'THD', '< 8%', 110),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Driver', 'Isolated', 120),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'CRI', 'Ra > 80–90', 130),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Efficacy', '110 lm/W', 140),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Lumen maintenance', '97% up to 10,000 h', 150),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Service life', '50,000 hours', 160),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Material', 'Aluminium + PC diffuser', 170),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Operating temp', '−20 °C to 45 °C', 180),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Certification', 'CE · UL · LM-80 · RoHS', 190),
  ((SELECT id FROM products WHERE slug = 'shade-double-40'), 'Warranty', '3 years (replacement)', 200),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Wattage', '18 W', 0),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Luminous flux', '1,980 lm', 10),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Type', 'Conceal type (round)', 30),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Cutout', 'Ø 170 mm', 40),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'IP', 'IP54', 50),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'panel-r-18'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Wattage', '24 W', 0),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Luminous flux', '2,640 lm', 10),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Type', 'Conceal type (square)', 30),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Cutout', '205 × 205 mm', 40),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'IP', 'IP54', 50),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'panel-s-24'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Wattage', '40 W', 0),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Luminous flux', '4,400 lm', 10),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'CCT', '4000 K', 20),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Type', 'Louver type', 30),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Size', '595 × 595 mm', 40),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'IP', 'IP54', 50),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'panel-l-40'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Wattage', '9 W', 0),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Luminous flux', '990 lm', 10),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Cap', 'E27', 30),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Type', 'A-shape', 40),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'IP', 'IP20', 50),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-9'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Wattage', '12 W', 0),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Luminous flux', '1,320 lm', 10),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'CCT', '3000 K', 20),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Cap', 'B22', 30),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Type', 'A-shape', 40),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'IP', 'IP20', 50),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'bulb-ac-12'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Wattage', '36 W', 0),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Luminous flux', '3,960 lm', 10),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Cap', 'E27', 30),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Type', 'T-bulb, finned heat sink', 40),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'IP', 'IP20', 50),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'bulb-t-36'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Wattage', '9 W', 0),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Luminous flux', '900 lm', 10),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Cap', 'E27', 30),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Type', 'DC bulb', 40),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Use', 'IPS, solar home system, battery backup', 50),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'IP', 'IP20', 60),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Input voltage', '12 V DC (10–15 V)', 70),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Frequency', '50–60 Hz', 80),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Output voltage', 'DC 12 V', 90),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Power factor', '—', 100),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'THD', '—', 110),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Driver', 'Isolated', 120),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'CRI', 'Ra > 80–90', 130),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Efficacy', '110 lm/W', 140),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Lumen maintenance', '97% up to 10,000 h', 150),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Service life', '50,000 hours', 160),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Material', 'Aluminium + PC diffuser', 170),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Operating temp', '−20 °C to 45 °C', 180),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Certification', 'CE · UL · LM-80 · RoHS', 190),
  ((SELECT id FROM products WHERE slug = 'bulb-dc-9'), 'Warranty', '1 year (replacement)', 200),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Wattage', '100 W', 0),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Luminous flux', '11,000 lm', 10),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'CCT', '5700 K', 20),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Type', 'UFO, die-cast aluminium', 30),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Beam', '120°', 40),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'IP', 'IP65', 50),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'hb-100'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Wattage', '150 W', 0),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Luminous flux', '16,500 lm', 10),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'CCT', '5700 K', 20),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Type', 'UFO, die-cast aluminium', 30),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Beam', '120°', 40),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'IP', 'IP65', 50),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'hb-150'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Wattage', '200 W', 0),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Luminous flux', '22,000 lm', 10),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'CCT', '5700 K', 20),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Type', 'UFO, die-cast aluminium', 30),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Beam', '90°', 40),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'IP', 'IP65', 50),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'hb-200'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Wattage', '7 W', 0),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Luminous flux', '770 lm', 10),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'CCT', '3000 K', 20),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Type', 'COB recessed, anti-glare', 30),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Cutout', 'Ø 75 mm', 40),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Beam', '24°', 50),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'IP', 'IP20', 60),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Input voltage', 'AC 85–265 V', 70),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Frequency', '50–60 Hz', 80),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Output voltage', 'DC 36–42 V', 90),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Power factor', 'PF > 0.96', 100),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'THD', '< 8%', 110),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Driver', 'Isolated', 120),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'CRI', 'Ra > 80–90', 130),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Efficacy', '110 lm/W', 140),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Lumen maintenance', '97% up to 10,000 h', 150),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Service life', '50,000 hours', 160),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Material', 'Aluminium + PC diffuser', 170),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Operating temp', '−20 °C to 45 °C', 180),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Certification', 'CE · UL · LM-80 · RoHS', 190),
  ((SELECT id FROM products WHERE slug = 'dl-7'), 'Warranty', '3 years (replacement)', 200),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Wattage', '12 W', 0),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Luminous flux', '1,320 lm', 10),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'CCT', '3000 K', 20),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Type', 'COB recessed, anti-glare', 30),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Cutout', 'Ø 90 mm', 40),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Beam', '24°', 50),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'IP', 'IP20', 60),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Input voltage', 'AC 85–265 V', 70),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Frequency', '50–60 Hz', 80),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Output voltage', 'DC 36–42 V', 90),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Power factor', 'PF > 0.96', 100),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'THD', '< 8%', 110),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Driver', 'Isolated', 120),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'CRI', 'Ra > 80–90', 130),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Efficacy', '110 lm/W', 140),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Lumen maintenance', '97% up to 10,000 h', 150),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Service life', '50,000 hours', 160),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Material', 'Aluminium + PC diffuser', 170),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Operating temp', '−20 °C to 45 °C', 180),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Certification', 'CE · UL · LM-80 · RoHS', 190),
  ((SELECT id FROM products WHERE slug = 'dl-12'), 'Warranty', '3 years (replacement)', 200),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Wattage', '20 W', 0),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Luminous flux', '2,200 lm', 10),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'CCT', '3000 K', 20),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Type', 'COB track head', 30),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Beam', '24° adjustable', 40),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Movement', '350° pan / 90° tilt', 50),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Track', '3-wire universal', 60),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'IP', 'IP20', 70),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Input voltage', 'AC 85–265 V', 80),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Frequency', '50–60 Hz', 90),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Output voltage', 'DC 36–42 V', 100),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Power factor', 'PF > 0.96', 110),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'THD', '< 8%', 120),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Driver', 'Isolated', 130),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'CRI', 'Ra > 80–90', 140),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Efficacy', '110 lm/W', 150),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Lumen maintenance', '97% up to 10,000 h', 160),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Service life', '50,000 hours', 170),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Material', 'Aluminium + PC diffuser', 180),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Operating temp', '−20 °C to 45 °C', 190),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Certification', 'CE · UL · LM-80 · RoHS', 200),
  ((SELECT id FROM products WHERE slug = 'tl-20'), 'Warranty', '3 years (replacement)', 210),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Wattage', '20 W', 0),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Luminous flux', '2,200 lm', 10),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Type', 'Slim die-cast, toughened glass', 30),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Beam', '120°', 40),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'fl-20'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Wattage', '50 W', 0),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Luminous flux', '5,500 lm', 10),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Type', 'Slim die-cast, toughened glass', 30),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Beam', '120°', 40),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'fl-50'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Wattage', '100 W', 0),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Luminous flux', '11,000 lm', 10),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Type', 'Slim die-cast, toughened glass', 30),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Beam', '120°', 40),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'fl-100'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Wattage', '200 W', 0),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Luminous flux', '22,000 lm', 10),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Type', 'Slim die-cast, toughened glass', 30),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Beam', '120°', 40),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'IP', 'IP66', 50),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Input voltage', 'AC 85–265 V', 60),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Frequency', '50–60 Hz', 70),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Output voltage', 'DC 36–42 V', 80),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Power factor', 'PF > 0.96', 90),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'THD', '< 8%', 100),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Driver', 'Isolated', 110),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'CRI', 'Ra > 80–90', 120),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Efficacy', '110 lm/W', 130),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Lumen maintenance', '97% up to 10,000 h', 140),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Material', 'Aluminium + PC diffuser', 160),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Operating temp', '−20 °C to 45 °C', 170),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Certification', 'CE · UL · LM-80 · RoHS', 180),
  ((SELECT id FROM products WHERE slug = 'fl-200'), 'Warranty', '3 years (replacement)', 190),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Rating', '16 A / 250 V', 0),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Gangs', '1 gang 1 way', 10),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Plate', 'Modern white PC', 20),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Material', 'V0 flame-retardant polycarbonate', 30),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Standard', 'IEC 60669', 40),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Size', '86 × 86 mm', 50),
  ((SELECT id FROM products WHERE slug = 'sw-1g'), 'Warranty', '1 year', 60),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Rating', '16 A / 250 V', 0),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Gangs', '2 gang 1 way', 10),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Plate', 'Modern white PC', 20),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Material', 'V0 flame-retardant polycarbonate', 30),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Standard', 'IEC 60669', 40),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Size', '86 × 86 mm', 50),
  ((SELECT id FROM products WHERE slug = 'sw-2g'), 'Warranty', '1 year', 60),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Rating', '13 A / 250 V', 0),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Type', '3-pin switched socket', 10),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Shutter', 'Child-safe shutter', 20),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Plate', 'Modern white PC', 30),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Standard', 'IEC 60884', 40),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Size', '86 × 86 mm', 50),
  ((SELECT id FROM products WHERE slug = 'so-13a'), 'Warranty', '1 year', 60),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Current', '32 A', 0),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Poles', '1P', 10),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Breaking capacity', '6 kA', 20),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Curve', 'C', 30),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Standard', 'IEC 60898-1', 40),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Mount', '35 mm DIN rail', 50),
  ((SELECT id FROM products WHERE slug = 'mcb-32'), 'Warranty', '2 years', 60),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Current', '63 A', 0),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Poles', '2P', 10),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Sensitivity', '30 mA', 20),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Type', 'AC', 30),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Standard', 'IEC 61008', 40),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Mount', '35 mm DIN rail', 50),
  ((SELECT id FROM products WHERE slug = 'rccb-63'), 'Warranty', '2 years', 60),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'Ways', '8 + neutral', 0),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'Rating', '63 A incomer', 10),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'Enclosure', 'Powder-coated steel', 20),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'IP', 'IP42', 30),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'Standard', 'IEC 61439-3', 40),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'Mount', 'Surface', 50),
  ((SELECT id FROM products WHERE slug = 'db-8'), 'Warranty', '2 years', 60);

-- ---------- spec sheets for the photographed products ----------
INSERT INTO product_specs (product_id, spec_key, spec_value, sort_order) VALUES
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Wattage', '36 W', 0),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Luminous flux', '3,600 lm', 10),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Type', 'Slim surface batten', 30),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Length', '1,200 mm', 40),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'IP', 'IP20', 50),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Material', 'Aluminium body + PC diffuser', 60),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Efficacy', '100 lm/W', 70),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Input voltage', 'AC 85–265 V', 80),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Frequency', '50–60 Hz', 90),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Power factor', 'PF > 0.96', 100),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'THD', '< 8%', 110),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Driver', 'Isolated', 120),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'CRI', 'Ra > 80–90', 130),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Service life', '50,000 hours', 140),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Operating temp', '−20 °C to 45 °C', 150),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Certification', 'CE · LM-80 · RoHS', 160),
  ((SELECT id FROM products WHERE slug = 'batten-36'), 'Warranty', '1 year (replacement)', 170),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Wattage', '12 W', 0),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Luminous flux', '1,080 lm', 10),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'CCT', '3000 K', 20),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'CCT options', '3000 / 4000 / 6500 K', 30),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Type', 'Surface mounted, no cutout', 40),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Beam angle', '36°', 50),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'IP', 'IP20', 60),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Material', 'Die-cast aluminium, white', 70),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Efficacy', '90 lm/W', 80),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Input voltage', 'AC 85–265 V', 90),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Frequency', '50–60 Hz', 100),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Power factor', 'PF > 0.96', 110),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'THD', '< 8%', 120),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Driver', 'Isolated', 130),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'CRI', 'Ra > 80–90', 140),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Operating temp', '−20 °C to 45 °C', 160),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Certification', 'CE · LM-80 · RoHS', 170),
  ((SELECT id FROM products WHERE slug = 'sdl-12-white'), 'Warranty', '1 year (replacement)', 180),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Wattage', '12 W', 0),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Luminous flux', '1,080 lm', 10),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'CCT', '3000 K', 20),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'CCT options', '3000 / 4000 / 6500 K', 30),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Type', 'Surface mounted, no cutout', 40),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Beam angle', '24°', 50),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'IP', 'IP20', 60),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Material', 'Die-cast aluminium, black + gold reflector', 70),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Efficacy', '90 lm/W', 80),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Input voltage', 'AC 85–265 V', 90),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Frequency', '50–60 Hz', 100),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Power factor', 'PF > 0.96', 110),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'THD', '< 8%', 120),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Driver', 'Isolated', 130),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'CRI', 'Ra > 80–90', 140),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Service life', '50,000 hours', 150),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Operating temp', '−20 °C to 45 °C', 160),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Certification', 'CE · LM-80 · RoHS', 170),
  ((SELECT id FROM products WHERE slug = 'sdl-12-black'), 'Warranty', '1 year (replacement)', 180),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Wattage', '25 W', 0),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Luminous flux', '1,400 lm', 10),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'CCT', '6500 K', 20),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Type', 'Half-spiral CFL', 30),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Cap', 'E27', 40),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Input voltage', 'AC 220–240 V', 50),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Frequency', '50 Hz', 60),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Service life', '8,000 hours', 70),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Material', 'Glass tube + PBT base', 80),
  ((SELECT id FROM products WHERE slug = 'cfl-25'), 'Warranty', '6 months (replacement)', 90);

-- ---------- editable site settings (Admin → Settings) ----------
INSERT INTO settings (setting_key, setting_value) VALUES
  ('company_name', 'OBD LIGHTING LTD'),
  ('company_name_bn', 'ওবিডি লাইটিং'),
  ('tagline', 'Total Lighting Solutions'),
  ('tagline_bn', 'টোটাল লাইটিং সলিউশনস'),
  ('phone', '01994999664'),
  ('whatsapp', '8801994999664'),
  ('email', 'Osram.mri@gmail.com'),
  ('address', 'House 404, Moni Mohol, Sayed Nogor, Vatara, Dhaka 1212'),
  ('address_bn', 'বাসা ৪০৪, মনি মহল, সাঈদ নগর, ভাটারা, ঢাকা ১২১২'),
  ('trade_licence', 'TRAD/DNCC/013204/2026'),
  ('hours', 'Saturday – Thursday, 9:00 am – 8:00 pm'),
  ('hours_bn', 'শনি – বৃহস্পতি, সকাল ৯টা – রাত ৮টা'),
  ('delivery_inside_dhaka', '80'),
  ('delivery_outside_dhaka', '150'),
  ('free_delivery_over', '5000'),
  ('warranty', '3 years (replacement)'),
  ('warranty_bn', '৩ বছর (রিপ্লেসমেন্ট)'),
  ('certifications', 'CE,UL,LM-80,RoHS'),
  ('about_text', 'Importer and supplier of LED lighting for homes, offices, factories and roads. Genuine product supply, wiring, installation and maintenance.'),
  ('about_text_bn', 'বাসা, অফিস, কারখানা আর রাস্তার জন্য LED লাইটের আমদানিকারক ও সরবরাহকারী। আসল পণ্য সরবরাহ, ওয়্যারিং, ইনস্টলেশন ও রক্ষণাবেক্ষণ।'),
  ('footer_note', 'Genuine stock · warranty card with every invoice'),
  ('footer_note_bn', 'আসল পণ্য · প্রতিটি ইনভয়েসে ওয়ারেন্টি কার্ড'),
  ('facebook', ''),
  ('youtube', ''),
  ('map_embed', ''),
  -- The home page slider. Up to 5 product slugs, in order; the star buttons
  -- in Admin -> Products rewrite this line. These five all have a real
  -- photograph, so the slider opens with pictures rather than drawings.
  ('hero_products', 'batten-36,fl-50,sdl-12-black,shade-double-40,bulb-ac-9');

-- The admin account is created by the setup script (npm run setup).
